all: Ass1_51_1a Ass1_51_1b

Ass1_51_1a:
	g++ Ass1_51_1a.cpp -o Ass1_51_1a -std=c++11

Ass1_51_1b:
	g++ Ass1_51_1b.cpp -o Ass1_51_1b -std=c++11

clean:
	rm -f Ass1_51_1a.exe Ass1_51_1a Ass1_51_1b.exe Ass1_51_1b